### ISSUE TITLE
Nesten Css

### ISSUE THREAD

**Issue by TimOosterveer** [IvarSchuyt/your-tribe-for-life-profile-card#2]
probeer te nesten in css zoals dit stukje code:

```css
  .personal_info {
    display: flex;
    flex-direction: column;
    justify-content: space-around;
    align-items: center;
    width: 35vw;
    height: 100%;

    & .name p {
      opacity: 0.7;
      text-align: center;
    }

    & .picture img {
      width: 100%;
      border-radius: 50%;
      border: 3px solid var(--textcolor);
    }
  }
```
